/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hongkailiu' at '11/04/16 7:55 PM' with Gradle 2.12
 *
 * @author hongkailiu, @date 11/04/16 7:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
